ALTER table public.membros
ALTER COLUMN nome TYPE varchar(80),
ALTER COLUMN nome DROP NOT NULL,
ALTER COLUMN apelido type varchar(20),
ALTER COLUMN apelido DROP NOT NULL,
ALTER COLUMN dt_nasc DROP NOT NULL,
ALTER COLUMN endereco TYPE varchar(80),
ALTER COLUMN endereco DROP NOT NULL,
ALTER COLUMN rg TYPE varchar(12),
ALTER COLUMN cpf TYPE varchar(11),
ALTER COLUMN pai TYPE varchar(80),
ALTER COLUMN mae TYPE varchar(80),
ALTER COLUMN mae DROP NOT NULL,
ALTER COLUMN st_civil TYPE smallint using st_civil::smallint,
ALTER COLUMN st_civil DROP NOT NULL,
ALTER COLUMN profissao TYPE varchar(30),
ALTER COLUMN profissao DROP NOT NULL,
ALTER COLUMN profissao DROP DEFAULT,
ALTER COLUMN tel_resid TYPE varchar(11),
ALTER COLUMN tel_com TYPE varchar(11),
ALTER COLUMN tel_celular TYPE varchar(11),
ALTER COLUMN email TYPE varchar(80),
ALTER COLUMN obs TYPE varchar(100),
ALTER COLUMN foto TYPE varchar(100);